
services:
  #mariadb
  mariadb:
    image: mariadb:sarif
    container_name: mariadb
    restart: always
    build: ./requirements/mariadb
    volumes:
      - ./mariadb:/var/lib/mysql
    env_file :
      - .env
    networks :
      - app-net

#nginx
  nginx:
    image: nginx:sarif
    container_name: nginx
    restart: always
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - ./wordpress:/var/www/wordpress
    networks:
      - app-net

#wordpress
  wordpress:
    image: wordpress:sarif
    container_name: wordpress
    restart: always
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    env_file :
      - .env
    networks:
      - app-net


volumes:
  mariadb:
   driver: local
   driver_opts:
      device: ~/data/mariadb
      type : none
      o : bind

  wordpress:
    driver: local
    driver_opts:
      device: ~/data/wordpress
      type : none
      o : bind

networks:
  app-net:
    driver: bridge