
# =====================
# SERVICES ============
# =====================
services:
  # 1️⃣ MariaDB — must start first
  mariadb:
    container_name: mariadb
    image: mariadb:sarif
    restart: always
    build: ./requirements/mariadb
    volumes:
      - mariadb-volume:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception

  # 2️⃣ WordPress — waits for MariaDB
  wordpress:
    container_name: wordpress
    image: wordpress:sarif
    restart: always
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress-volume:/var/www/html
    env_file:
      - .env
    networks:
      - inception

  # 3️⃣ Nginx — depends on WordPress (PHP backend)
  nginx:
    container_name: nginx
    image: nginx:sarif
    restart: always
    build: ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress-volume:/var/www/html
    networks:
      - inception

# =====================
# VOLUMES =============
# =====================
volumes:
  mariadb-volume:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/mariadb
      o: bind

  wordpress-volume:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/wordpress
      o: bind

# =====================
# NETWORKS ============
# =====================
networks:
  inception:
    name: inception
    driver: bridge
